RNA-seq/reproducibility_cmdline.md
One way to start to approach this topic.
=> Add initial draft of shell scripting

scRNA-seq/02-tag-based_pre-processing_scRNA-seq.md
Added some minor stylistic and explanation changes to 02-notebook. Most changes correspond to the change to a smaller, subsetted fastq file to run Alevin on.
=> 02-notebook wording and filename edits

.gitignore, RNA-seq/07-bulk_rnaseq_exercise.Rmd
Closes #79 
I'm adding only the Rmd file. I've added a `.gitignore` to ignore the notebook HTML files because they're not particularly helpful especially in the GitHub pages setting.
=> Add bulk RNA-seq exercise notebook

LICENSE.md
This PR addresses #65 and adds this BB-CY license to this training material.
=> Add BB-CY license

.gitignore, machine-learning/05-machine_learning_exercise.Rmd
This is the machine learning exercise notebook I would like to present to training participants.
=> Add machine learning exercise notebook - participant version

RNA-seq/01-qc_trim_quant.md, RNA-seq/04-nb_cell_line_tximport.md
Uncovered during run through on my MacBook.
=> Bulk RNA-seq scripts directory fix

scRNA-seq/00-scRNA-seq_introduction.md
Small PR, to close #116 
These two papers have come out recently so I added them to the Lit list in the 00 scRNA-seq guide. 
[Lafzi et al. _Nature Protocols_ 2019](https://doi.org/10.1038/s41596-018-0073-y)  
[Luecken & Theis _Mol Syst Biol._](https://doi.org/10.15252/msb.20188746)
But I also re-ordered the papers to be from most recent year first and then by author names alphabetically.
=> Adding two papers to the single cell 00 document

intro-to-R-tidyverse/README.md
This PR addresses [issue #76](https://github.com/AlexsLemonade/training-admin/issues/76) filed in the training-admin repository. 
This `README.md` file was added to foreshadow the contents of the training module.
=> Addition of `README.md` to Intro-to-R-tidyverse training module

scRNA-seq/README.md
This issue addresses the scRNA-seq bullet point of [training-admin item #76](https://github.com/AlexsLemonade/training-admin/issues/76).
I followed the basic [template created by the RNA-seq README](https://github.com/AlexsLemonade/training-modules/pull/150).
=> scRNA-seq README

RNA-seq/01-qc_trim_quant.md, intro-to-R-tidyverse/01-intro_to_r.Rmd, intro-to-R-tidyverse/02-intro_to_tidyverse.Rmd
A couple typos and minor clarifications.
=> Minor edits to training modules

intro-to-R-tidyverse/03-intro_to_r_exercise.Rmd
Fix what I think is a small typo that caused confusion.
=> `mouse_ids`s -> `mouse_id`s

.gitignore, intro-to-R-tidyverse/01-introduction-base-R.Rmd, intro-to-R-tidyverse/01-introduction-base-R.nb.html
This includes a few minor edits that was easier for me to just make and push as a PR to your PR. 
I still want to do the more major restructure of moving variable types to the end as a kind of addendum, and perhaps adding a touch of dplyr as the final part of this notebook.
=> Josh's minor edits to NB 1

.gitignore, intro-to-R-tidyverse/README.md
This PR closes #175 as well as updating the .gitignore references to these notebooks. 
I also tried to update the wording to reflect the revised order and content of the notebooks.
=> Intro to R notebook references in the gitignore and README

intro-to-R-tidyverse/00c-good-scientific-coding-practices.md
Closes https://github.com/AlexsLemonade/training-admin/issues/210
99% of this document is copied from [this section in the previous intro to R notebook](https://github.com/AlexsLemonade/training-modules/blob/c678f4826b9e3663eb16a43aedc5d9bf5649ed61/intro-to-R-tidyverse/01-intro_to_r.Rmd#L556. )
Besides that I added a couple articles related to the topic.
=> Scientific coding practices document

RNA-seq/00b-additional_approaches.md
`RNA-seq/00b-additional_approaches.md` needed to be updated to 1) remove references to Docker and 2) to reflect the `v1.0.0`+ Salmon changes - I'm now linking out to a selective alignment tutorial from the Salmon folks.
=> Update bulk RNA-seq ref document for virtual pilot

RNA-seq/01-qc_trim_quant.md, RNA-seq/scripts/run_SRR585570.sh
This came up in the dry run/stress test today.
=> mkdir -p for the fastp output

virtual-setup/working-with-your-own-data.md
Closes https://github.com/AlexsLemonade/training-admin/issues/212
Particularly related to this comment: https://github.com/AlexsLemonade/training-admin/issues/212#issuecomment-620607472
I'm unsure where the appropriate place for this warning is, or if we want it to be so upfront at all.
=> Working with data: Add 6 month warning

virtual-setup/mac-instructions.md
=> Caught a tiny formatting error

.github/workflows/build-docker.yml
I made a mistake by including this, it is not necessary!
=> No Slack notification for Docker build upon PR

CONTRIBUTING.md
I forgot to update `CONTRIBUTING.md` as part of #395 !
=> Document fail if any errors in spell check

.github/workflows/make-live.yml
rendering=TRUE should be default now that it works!
=> GHA make it live: Make rendering=TRUE default

components/dictionary.txt, scRNA-seq/README.md
The single cell module readme never got updated with the latests versions of the modules. This PR fixes that.
I removed time estimates, because those are probably no longer accurate!
=> Updates to readme links

components/dictionary.txt, intro-to-R-tidyverse/01-intro_to_base_R.Rmd, intro-to-R-tidyverse/02-intro_to_ggplot2.Rmd, intro-to-R-tidyverse/03-intro_to_tidyverse.Rmd, scRNA-seq/05-clustering_markers_scRNA.Rmd, scRNA-seq/06-overrepresentation_analysis.Rmd, scRNA-seq/exercise_02-scrna_clustering.Rmd
This PR started life as an updated to links to the OSCA notebooks and tidyverse cheatsheets, but a couple other things snuck in. 
These were:
- I updated the intro 03 notebook to one sentence per line (not sure why it was the lone holdout I saw)
- I added a note about the native pipe.
=> Update links to cheatsheets and OSCA

intro-to-R-tidyverse/01-intro_to_base_R.Rmd
This PR fixes some small typos and explanations in the `01-intro_to_base_R` notebook.
=> Miscellaneous fixes to 01-intro_to_base_R

scRNA-seq/02-filtering_scRNA.Rmd
Very minor updates to second scRNA-seq notebook, including comments for context and 1 chunk name typo.
=> Small cleanups for 02_scRNA-seq

intro-to-R-tidyverse/03-intro_to_tidyverse.Rmd
This PR fixes some small typos and explanations in the `03_intro-to-tidyverse.Rmd` notebook.
This PR does not address issue #533 (because that fix needs to happen elsewhere), but worth being aware of this issue while looking at this notebook.
=> Miscellaneous fixes to 03_intro-to-tidyverse

.github/workflows/spell-check.yml, .gitignore, RNA-seq/.gitignore, components/dictionary.txt, intro-to-R-tidyverse/.gitignore, machine-learning/.gitignore, scRNA-seq-advanced/.gitignore, scRNA-seq-advanced/README.md, scRNA-seq-advanced/scRNA-seq-advanced.Rproj, scRNA-seq-advanced/setup/README.md, scRNA-seq/.gitignore, scRNA-seq/04-dimension_reduction_scRNA.Rmd, scripts/spell-check.R
This PR is mostly just  to set an initial directory and starting content for the advanced single cell module. 
I created a brief README, as well as a `setup` folder with its own readme file and a `data` directory that is at the moment empty. 
I had trouble with naming, and don't love the folder name I chose... I'm very open to suggestions. I kind of wanted to make sure that this directory sorted after `scRNA-seq`, but I may be thinking too hard about that.
I requested all people who I expect to be writing material to review this, mostly because I want all of you to be aware of the content and structure, as this will undoubtedly come up in future issues and PRs!
=> Add structure for advanced single cell module

scRNA-seq-advanced/03-dataset_integration.Rmd
Related to #570 
This PR takes the next steps in the integration instruction notebook. Specifically:
- Library --> sample, except for a few places where I thought it made more sense to keep library. I don't feel strongly about those places though if anyone disagrees!
- Solidified the second half of the notebook **Integration** section. I envision a lot of the discussion happening here during training, so I tried to add some small quick interpretations with the goal that they will lead into that discussion with participants.
- Other small phrasing cleanups I noticed along the way
Here's the HTML: [03-dataset_integration.nb.html.zip](https://github.com/AlexsLemonade/training-modules/files/10279376/03-dataset_integration.nb.html.zip)
Note that the next PR for this notebook will update …
=> Integration instruction notebook: Integration

scRNA-seq-advanced/04-differential_expression.Rmd
Stacked on #628
Found a few more typos in the DE notebook and also updated everything here to `scRNA-seq` to mirror what's happening in #628
=> Minor DE Fixes 

scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd, scRNA-seq-advanced/02-celltype_assignment.Rmd, scRNA-seq-advanced/03-dataset_integration.Rmd, scRNA-seq-advanced/04-differential_expression.Rmd
I started here with just converting headings to all be sentence case, but then added a few more subheadings, notably in the 04 notebook, and changed header levels in a couple places.
The 04 notebook headings are up for debate, so @allyhawkins thoughts on those will be particularly helpful there
=> Updating some headers in scAdvanced

scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd, scRNA-seq-advanced/02-celltype_assignment.Rmd, scRNA-seq-advanced/03-dataset_integration.Rmd, scRNA-seq-advanced/04-differential_expression.Rmd
Looking at rendered notebooks, I found some broken links and some that were just formatted oddly. This fixes those. Hopefully.
=> A few link fixes

scRNA-seq-advanced/03-dataset_integration.Rmd
Add a missing `r` to the integration notebook text.
=> purr -> purrr

scripts/link-data.sh, scripts/syncup-s3.sh
Closes #719 
Does what it says!
Note that if we prefer, I can comment out these lines instead of wholesale deleting, but it seemed to me like we're ready to delete..?
=> Remove darmanis data from scripts

intro-to-R-tidyverse/01-intro_to_base_R.Rmd, intro-to-R-tidyverse/02-intro_to_ggplot2.Rmd, scRNA-seq/01-scRNA_quant_qc.Rmd, scRNA-seq/03-normalizing_scRNA.Rmd, scRNA-seq/05-clustering_markers_scRNA.Rmd, scRNA-seq/06-celltype_annotation.Rmd
Closes #727 
This PR fixes the training fixes that need to be fixed, since I heard you like fixes in your fixes. Here I've handled the majority of comments in #727, and for any comments _not_ taken care of here, I've opened a separate issue. In addition, there's one change I made here that is not noted as a comment in #727 - there was an empty live chunk in the ggplot2 notebook, so I filled it in with the "solution."
Most of these changes are very small and can still be tweaked if we want!
=> May 2023 training fixes

scRNA-seq/03-normalizing_scRNA.Rmd
I posted this [comment](https://github.com/AlexsLemonade/training-modules/issues/598#issuecomment-1576594660), and then promptly couldn't help myself. In other words...this is just to say......
```
I have removed
the vector formatting
that was given
to `dplyr::select()`
and which
we probably 
didn't actually need to do
for this workshop
Forgive me
it was so quick 🍬 
so small
and so easy
```
ASAP after this I will...
- rerun the notebook rendering
- confirm this is the only new change, merge in
- release the ~kraken~ `2023-june` tag
CC @jashapiro for extra notification given the timing 🙃
=> Update a dplyr::select() usage - just column names

renv.lock
Before I complete https://github.com/AlexsLemonade/training-admin/issues/1084, I wanted to capture a couple more recent updates that were causing trouble in a docker image.
No major changes here, just a couple updates to bioconductor packages (I expect we will want to do one more round of updates before the next release, as little bug fixes come in)
=> A couple more package updates

.github/workflows/make-live.yml, .github/workflows/render-rmds.yml, .github/workflows/spell-check.yml, components/dictionary.txt
Closes #765
Closes #763
Here I am updating the docker image for rendering notebooks (and creating the live versions) as well as adding our fancy new spellcheck action
=> Update actions to use new Docker images and spellcheck

intro-to-R-tidyverse/01-intro_to_base_R.Rmd
Fixing this - https://github.com/AlexsLemonade/training-modules/pull/793/files#r1709666489
=> Remove extra opening parenthesis

scRNA-seq-advanced/02-dataset_integration.Rmd
Closes #802 
This PR updates a sentence (or two) in the notebook to be more open-ended and less prescribed about the harmony results, which are slightly different in the new harmony version in our environment. This wording also has the benefit of probably never needing to be modified again and will remain robust in the face of future harmony versions/changes!
=> Update integration notebook text

renv.lock
It occurred to me that this is probably necessary for #809 to go in.
=> Move renv changes for AUCell to own branch

renv.lock, renv/activate.R
Just a little PR to keep renv up to date, since it turned out that the version we had on the server by default was already 1.0.11.
=> Update renv to 1.0.11

scRNA-seq-advanced/03-differential_expression.Rmd
Really small, but worth the change.
=> Fix small typo in 03 notebook

intro-to-R-tidyverse/01-intro_to_base_R.Rmd
I caught one more spot to fix in the intro materials - https://github.com/AlexsLemonade/training-modules/issues/798#issuecomment-2296906749
This PR corrects the variable name as the comment indicates. Also, looks like whitespace got eaten up, so turn off whitespace for review to see the diff of interest!
=> Fix variable name

CONTRIBUTING.md
Closes #840 
Stacked on #847
This PR adds some content to our CONTRIBUTING file focusing on notebook organization and style guide concepts. I wanted to add a few more details here without overhauling the document, so I added a smidge about overall notebook organization and a couple bullets for style to just give that section a bit more content. Please let me know if you think more changes would be helpful, but I'm hoping these small additions are enough to make this document a little more forward-facing.
=> Update CONTRIBUTING style section

components/dictionary.txt, scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd, scRNA-seq-advanced/02-dataset_integration.Rmd, scRNA-seq-advanced/03-differential_expression.Rmd, scRNA-seq-advanced/04-gene_set_enrichment_analysis.Rmd, scRNA-seq-advanced/05-aucell.Rmd
Towards #830 
This PR updates notebooks in `scAdvanced` as commented in #830. I believe I addressed all notebook-related comments here. The other comments in this issue were about slides, one of which I addressed ("will it integrate"?) and the other I tossed over to @jashapiro.
Note for this comment: https://github.com/AlexsLemonade/training-modules/issues/830#issuecomment-2536227840
- I did not change `dir()` to `list.files()`, here or anywhere else (there's spots in the intro r module & cheatsheet that one could change as well). Let me know if you think that's worth doing. To start this PR, it seemed overkill to me.
- Using `full.names  = TRUE` doesn't actually make sense since there are many more `.rds` files in the input directory than just the four we're reading in, and we'd have to …
=> Material updates from December 2024
