AlexsLemonade/training-modules

- scRNA-seq/02-tag-based_pre-processing_scRNA-seq.md
I've added links to already existing example alevinQC reports in this repository. Also updated the transcriptome index reference to be the name of the mouse transcriptome index that should be created from `training-txome-prep` repository.
> add alevinQC links

- LICENSE.md
Following the precedent set by the [refinebio-examples PR discussion](https://github.com/AlexsLemonade/refinebio-examples/pull/86) I'm adding the same type of multi-license to the training-modules, since this repo is also mostly made of notebooks.
> Add same multi-license that is in refinebio-examples

- RNA-seq/06-bulk_rnaseq_exercise.Rmd
This PR is parallel to the [exercise-notebook-answers PR #5](https://github.com/AlexsLemonade/exercise-notebook-answers/pull/5) in accordance with the [issue #4](https://github.com/AlexsLemonade/exercise-notebook-answers/issues/4) of that repo. 
Essentially the filtering of all the objects is removed, and instead the comparison is specified in the `results(ddset)` bit.
> Parallel updated rearranged RNA-seq exercise blank notebook

- .gitignore
- RNA-seq/00a-reproducibility_cmdline.md
- RNA-seq/00b-additional_approaches.md
There are several methods/approaches I considered adding to the bulk RNA-seq module. I decided the addition of these approaches would tend to overwhelm folks with information (MultiQC), be less straightforward/commonly used than what we currently present (tximeta), or the computational requirements were inappropriate for the setting (selective alignment with decoy sequences). 
I've chosen instead to add information about them to a new file added with this PR: `RNA-seq/00b-additional_approaches.md`. Note that the approaches are introduce in order of difficulty/departure from training content.
The inclusion of this document has a few advantages in my mind:
* Interested participants can visit or revisit this document to learn more and experiment with these other methods. I'm willing to bet …
> Add an "additional approaches" reference markdown to bulk RNA-seq

- intro-to-R-tidyverse/03-intro_to_r_tidyverse_exercise.Rmd
In line 121, the metadata to be stored into the variable in this step of the intro_to_R_tidyverse_exercise notebook was clarified to be the renamed metadata from the previous step. The line, "Hint: `metadata_clean` should be placed before your first pipe operator" was also added to steer participants away from using the original metadata.
> Edit to `Intro_to_R` exercise notebook instructions

- docker-install/README.md
- intro-to-R-tidyverse/03-intro_to_r_tidyverse_exercise.Rmd
Added more context to Step 6 in the Docker Install instructions to encourage increasing resources but also to advise against using the maximum resources. 
"If you are able to provide more than 8GB of RAM, do so. However, be careful not to allot your computer's maximum RAM capacity."
> More context added to step 6 to advise against maximum RAM usage #118

- README.md
The last merge had cheatsheet links that produced an error in the README. 
These links have been fixed in this commit.
> Fix links to cheatsheets in README

- RNA-seq/README.md
To address https://github.com/AlexsLemonade/training-admin/issues/56 we need to provide useful links to the training materials. @dvenprasad and I discussed, and it seems most feasible to link from the CCDL website to the folder in training-modules. Then each folder in training-modules would provide links to the materials covered during that module. These links are to the items that comprise the modules on the schedule. This is my attempt to put together a first one for our RNA-seq exercises. Once we like it, we can use it as a template for the others.
> Create RNA-seq readme file.

- machine-learning/README.md
This PR addresses [issue #76](https://github.com/AlexsLemonade/training-admin/issues/76) filed in the training-admin repository. 
This adds a `README.md` file to the `machine-learning` training module to foreshadow the contents of the module.
> Addition of `README.md` to machine-learning training module

- README.md
This PR addresses issue [#79](https://github.com/AlexsLemonade/training-admin/issues/79) in the `training-admin` repository.
The training background slides were moved to the CCDL's GSuite and therefore the links to the slides in `README.md` are being updated in this PR.
> Update links to background slides in `training-modules/README.md`

- virtual-setup/README.md
- virtual-setup/linux-instructions.md
- virtual-setup/mac-instructions.md
- virtual-setup/rstudio-login.md
- virtual-setup/slack-procedures.md
- virtual-setup/windows-instructions.md
- virtual-setup/zoom-procedures.md
Here I've put together a series of (mostly blank!) markdown documents so folks can get an idea of the structure I'm envisioning for the `virtual-setup` module. We'd then link to these markdown documents from the specific training's wiki. A downside of this approach is that we won't have everything "all in one place," but a big advantage is that it will be considerably easier to maintain. For things like the Slack and Zoom procedures, I think we should plan to spend some time during the first day of instruction covering these documents.
> Stub in virtual-setup

- virtual-setup/slack-procedures.md
In the workshop structure documentation I'm writing up for the wiki in https://github.com/AlexsLemonade/2020-may-training, we're going to instruct participants to Slack DM an instructor if they have a problem with their RStudio credentials. I'm adding that into the Slack procedures here as well.
> Add note about RStudio credentials to Slack procedures

- intro-to-R-tidyverse/04a-intro_to_R_exercise.Rmd
- intro-to-R-tidyverse/04c-intro_to_tidyverse_exercise-part-2.Rmd
The original instructions surrounding ggthemes, was a little too open ended and lead participants to think they needed to install the ggthemes package which often lead them on a rabbit hole that was not intended. 
With it's [companion PR on `exercise-notebook-answers`](https://github.com/AlexsLemonade/exercise-notebook-answers/pull/23), this closes https://github.com/AlexsLemonade/exercise-notebook-answers/issues/22
> Update ggtheme wording in accordance with exercise notebook PR

- scripts/make-live.R
Before we turn notebook rendering into part of a github action as proposed in #226, I thought we could do the first step of https://github.com/AlexsLemonade/training-modules/pull/223#issuecomment-638170906 and make rerendering the html part of the make-live script. So here it is.
I had a thought about making this optional, but decided it was better to just have it run every time, even if that is potentially a bit slow. If we are running this script, we should be just about to push our latest changes, so rerunning everything cleanly seems a good idea.
> Add rendering of the full notebook to make-live script

- pathway-analysis/01-overrepresentation_analysis.Rmd
added spaces so there are no `{{` tags for jekyll to get upset about
> Placate jekyll

- .gitignore
- scRNA-seq/.gitignore
- scRNA-seq/setup/README.md
This PR does some minor cleaning of .gitignore files and adds instructions to the setup module about what symbolic links need to be created for the scRNA-seq module after checking out the repository.
> Add instructions for setup of links

- machine-learning/README.md
Origins: #257 
With the revamping of machine-learning module, the README needed to be updated in accordance. 
The main changes to the README here are: 
- Notebook list and its links updated for new material 
- Exchange Northcott et al summary for OpenPBTA dataset summary
All links work, except for the `Additional exercises` one because the notebook has not been merged yet (will be on #269 ) but it is the correct link for when that is merged.
> Update the machine learning README to reflect the changes

- machine-learning/machine-learning.Rproj
I am planning on using projects for both modules this training. I added one for `pathway-analysis` on the open PR for that module (https://github.com/AlexsLemonade/training-modules/pull/281/commits/376fa69e6df8e3c63e936a1dc12184a63cf1805c).
> Add machine-learning Rproj

- intro-to-R-tidyverse/01b-intro_to_base_R_exercise.Rmd
During the first day of the PGH workshop, one of the participants noticed a typo in the `01b-intro_to_base_R_exercise.Rmd` file. 
This PR fixes the typo at [line 120](https://github.com/AlexsLemonade/training-modules/blob/ddc9c76e03aaf147fb2f011490ea6aec835de064/intro-to-R-tidyverse/01b-intro_to_base_R_exercise.Rmd#L120): "What about the `refine_bio_accession_code` column?" 
where `refine_bio_accession_code` should be `refinebio_accession_code`. 
Note that I also filed a PR to fix this in the `exercise-notebook-answers` repo: AlexsLemonade/exercise-notebook-answers#42
> Fix typo in `01b-intro_to_base_R_exercise.Rmd`

- .github/workflows/build-and-push-docker.yml
- CONTRIBUTING.md
⚠️ **depends on #302, review that first** 🚨 stacked changes 🚨 
Here I'm adding a GHA that will build the Docker image and push it to Dockerhub every time a PR gets merged into `master` (`.github/workflows/build-and-push-docker.yml`). It doesn't use caching, which seems like it will not be a problem time-wise because one does not have to wait for it to run _before_ merging. 
Closes #298.
> Add workflow that builds and pushes the Docker image upon merges

- renv.lock
There was a bit of rabbit hole here about why MRAN is appearing when I install packages on my Mac, but it seems to be working out just fine... letting it install from MRAN did not modify the renv.lock in any way. 🤷‍♂️ 
So here I am adding an explicit CRAN entry, for what probably is no reason, but seems like a Good Thing™
> Make an explicit CRAN entry in the repositories list

- .Rprofile
- CONTRIBUTING.md
- renv.lock
I noticed this was needed while developing #304 using `ccdl/training_dev:latest`. Because we use a `rocker/tidyverse:4.0.3` base image, the RSPM URL is set by the container to `latest` until the next R version is released. That means when I went to install the libraries required for spell check, the RSPM URL would be "displaced" by the URL the base image is set to use in the lockfile. 
My solution to this, since we already have a lockfile tracked here, is to use the repositories in `renv.lock` to set the repos when you open the project by adding those steps to `.Rprofile`. We only have the RSPM repo at the moment, but I tried to do this in a way that is more general with `purrr`. I can say that this works as intended: when I use `install.packages("spelling")` and then `renv::snapshot()`, …
> Set repos in .Rprofile using the lockfile

- scripts/spell-check.R
I noticed when running the spellcheck locally that I got a huge number of errrors. This was because it was checking all the markdown files in the renv packages. So here I add a script to exclude that folder from examination (also speeds up local runs!)
I also added the emoji error, and that seems to have worked. Huzzah!
> Exclude renv and add emoji

- .Rprofile
- renv/.gitignore
- renv/settings.dcf
Apparently you should never use `libarary(renv)` because it masks `base::load()`, which does bad things. But if you don't the docker image gets unhappy, because it loses its connection to the cache when you start a new container. So we need to set `use.cache: FALSE` in `renv/settings.dcf`.
This means that the `renv/library` directory may get large, as it is keeping its own copy of all of the packages, but that is a local problem (hopefully).
> Fix renv conflicts

- scripts/link-data.sh
When I made the link-data.sh script, I had a small bug where I put the link destination for the salmon short index in the wrong place (where the tx2gene file should be!). This should fix that!
> Fix short_index link destination

- components/dependencies.R
- renv.lock
This PR updates renv and dependencies.R to add modules and hidden dependencies required for running all notebooks. 
This is the first of several stacked PRs that will hopefully result in make-live.R working on the server current package versions and linked files.
> Make make-live work: 1/n update renv for all modules

- RNA-seq/README.md
- intro-to-R-tidyverse/README.md
- machine-learning/README.md
- pathway-analysis/README.md
- scRNA-seq/README.md
This PR addresses issue #325 by adding the estimated times to complete each instruction notebook to the each training module's `README.md` file, as well as the estimated total time of completion for that module (instruction wise).
Note that I used the latest vimeo instruction videos for each notebook to record said estimated times.
I excluded breaks, but included instances where we had to wait for a step to complete running (not sure if this time should also be excluded but I thought we might want it in there).
Also note that, for the last two notebooks of the machine learning module I added very rough estimates based on my time of completion (and the time taken to complete the previous module's notebooks) as the `03-openpbta_PLIER.Rmd` notebook was not completed in the instruction video …
> Add estimated times of completion to modules' `README`

- Dockerfile
This PR adds the AWS command line tools which we need for syncing data to the `training_dev` docker image.
I also figured out that we can reduce the image size by getting rid of the cache that renv makes for the root user and is never actually used.
> Add AWS and shrink Docker image size

- renv.lock
Second attempt to add tximeta to the renv.lock file. #361 was the first attempt, cherry picking was not ideal. 
In this attempt, I created a branch of off master, then just git checked-out the renv.lock file from `cansavvy/tximeta`
`git checkout cansavvy/tximeta renv.lock`
> Add renv.lock that has tximeta

- scripts/make-live.R
It seems that new.env() is not sufficient to prevent namespace conflicts between rendered notebooks, so I added a little wrapper function to clean up the namespace after rendering each notebook. 
I think it works (tested locally), but it still needs CI testing!
> Update make-live.R to clean up after rendering

- .github/workflows/make-live.yml
- .github/workflows/render-rmds.yml
- CONTRIBUTING.md
- scripts/make-live.R
- scripts/render-live.sh
This PR aims to simplify make-live.R to work on only one notebook at a time, moving the list of files and loop to `render-live.sh`. The goal here is to allow each notebook to run in its own very clean notebook environment. 
~~*Draft status means that documentation updates and application to all workflows are still incoming, but I want to test the mechanics!*~~
This seems to work now, so let's go!
closes #377
Have a look, let me know if there is more documentation to add.
~~I am going to save checking the PLIER notebooks for whoever wants to try their hand at #356; it may be as simple as uncommenting those notebooks!~~
Tested uncommenting, and it seems to run! (Not speedy, but it runs!)
Two 🐦 one 🍞 ! 
Closes #356 (it seems)
> Wrap make-live.R

- .github/workflows/make-live.yml
This PR is an attempt to solve #381 by adding the docs bot token that we had already created to the pull request step of the make-live action. This should make a PR from this workflow trigger the spellcheck action.
I have not tested this, because it seemed like making the changes for automated running would be more trouble than it was worth. I though maybe we could just merge this, test it, and revert the changes if it doesn't work.
> Add docs bot token to make-live

- .github/workflows/render-rmds.yml
This PR is designed mostly to prevent PRs from auto-rendered scripts from triggering another rendering test. Those scripts will change the `-live` notebooks, but not the source notebooks. So if we exclude live notebooks, we should be able to merge auto-render PRs faster. 
For future use, I also exclude the exercise notebooks.
> Restrict rendering  test to notebook changes

- .github/workflows/spell-check.yml
- components/dictionary.txt
We used to "allow" three spelling errors, partly because there was some kind of whitespace issue that caused extra "errors." This is no longer the case though, so I don't see a reason to have the number be as high as 3. 
If we take a look at the GHA results from #200: https://github.com/AlexsLemonade/training-modules/runs/1988578820?check_suite_focus=true
We have 3 spelling errors:
```
word	file	lines
AssayNames	RNA-seq-cheatsheet.md	77
Ensembl's	00c-tximeta_other_species.Rmd	66,74
linkedTxome	00c-tximeta_other_species.Rmd	42
```
With a lower spelling error tolerance, two of these would have probably been resolved during #372. Super minor thing, but my thought is it is better to add things to the custom dictionary as we need them (and/or the material is fresh in the PR author's head) …
> Lower number of spelling errors "allowed"

- renv.lock
Here's what I did per @jashapiro's recommendation to 'trick' renv into thinking we are using these packages that we aren't using on this branch but are using on #403 and #405
1. Checked out this new branch from master
2. `renv::restore()`
3. Installed `palmerpenguins` package
4. Added `palmerpenguins` and `EnhancedVolcano` to dependencies.R
5. Ran `renv::snapshot()` 
6. Then I commit only renv.lock
> Add penguins to renv.lock

- components/dependencies.R
- renv.lock
In an upcoming PR, I will be using mouse data in a pathway analysis notebook and therefore require `org.Mm.eg.db`. We've installed `org.Dr.eg.db` and `org.Cf.eg.db` in the training image before, but we don't (yet) use them during instruction. I've added them to `components/dependencies.R` as a result.
> Add AnnotationDBI packages for non-human organisms to lockfile

- components/dependencies.R
- renv.lock
I only noticed this when looking at the diff for https://github.com/AlexsLemonade/exercise-notebook-answers/pull/83. Here's a link to the specific line: https://github.com/AlexsLemonade/exercise-notebook-answers/pull/83/files#diff-137b8d6317cf78433671f1a2b5026b1cb567602e5f45f2f802283e94bb41dae4R535
We apparently need `hexbin` for the plots in the first bulk RNA-seq exercise notebook.
> Add hexbin to renv

- components/dependencies.R
- renv.lock
This PR just adds alevinQC to the training renv, but there were some other updates that came along as I did that, so I figured I might as well incorporate them as well.
> add alevinQC to renv and minor version updates

- scripts/link-data.sh
- scripts/syncup-s3.sh
This PR links the data for `alevin-quant/10X_P7_12` to the training-modules directory. This is the mammary gland data that we will be using for the scRNA-seq day 1 exercise notebook.
> Add link for data used in scRNA-seq day 1 exercise notebook

- scRNA-seq/setup/cellmarker_genes.Rmd
- scRNA-seq/setup/cellmarker_genes.nb.html
My current plan is to use mouse data for the single-cell pathway analysis exercise notebook. I wanted to give folks the option to use the CellMarker resource during that exercise, as it is intended to be pretty open-ended. I revised the CellMarker prep notebook to also clean the mouse data. Because the shell scripts (e.g., S3 sync, link data) act on the directory level, no changes are required there.
> Revise CellMarker prep to include mouse

- CITATION.cff
Currently missing an ORCID and possibly a middle initial for @allyhawkins, but this is adding a `CITATION.cff` file to this repository. 
The order is in order of the contributors graph for this repository: https://github.com/AlexsLemonade/training-modules/graphs/contributors
With the exception that I am last author.
> Initial draft of CITATION.cff

- RNA-seq/README.md
- intro-to-R-tidyverse/README.md
- pathway-analysis/README.md
- scRNA-seq/README.md
Closes #499. 
We changed our naming conventions for our exercise notebooks, so some of the links were broken. I went through all of the READMEs for material we've taught this year (read: not `machine-learning`) and updated the exercise notebook links. How we talk about these is not that consistent, but I figure that is a problem for another day and it is better to have links that are not broken!
> Fix links to exercise notebooks in module READMEs

- Dockerfile
- renv.lock
- renv/.gitignore
- renv/activate.R
For some of the more recent changes to scpcaTools, we needed to add R 4.1.2 to the server. (We probably could have gotten away with R 4.1.1, but I went ahead with 4.1.2). The default environment remains 4.0.3, but we will at some point want to switch. In preparation for that, I started to test that we could get all package updates & rebuild the renv environment as well as create a docker image that uses the same version of R and the same package versions.
This draft PR includes those changes. 
At the moment it uses the `latest` tag for the RStudio Package manager CRAN mirror, but this will presumably need to be updated when the Docker image for R 4.1.2 is frozen upon release of 4.1.3 (or whatever version is next). Or maybe leaving it at latest is okay, now that we are using renv? Leaving …
> Update Renv & docker for R 4.1.2

- intro-to-R-tidyverse/02-intro_to_ggplot2.Rmd
Closes #525 
Thanks @sjspielman for filing #525, as I noted on there (https://github.com/AlexsLemonade/training-modules/issues/525#issuecomment-1058110937), I do believe that the chunk with the first instance of the `labs()` function should be made live in the intro to ggplot2 notebook, and this is what this PR does.
I do not feel strongly about making the remaining chunks added in #522 live, but I would be happy to if other folks feel strongly about it!
> Make `labs()` chunk live in intro to ggplot2

- components/dependencies.R
- renv.lock
For some reason the `markdown` package was not included in the `renv.lock` file, which meant that it was not installed by default. As the RStudio prompt to install it when needed is pretty straightforward, this is thankfully not a big deal, but for the future, I manually installed the package so everyone should have it in the future, and here I am adding it to `renv.lock` so that future docker images will have it as well.
Update: Docker images are actually mostly unaffected, as `markdown` is included in the `rocker/tidyverse` base, so this is really only for the server's benefit.
Updating the `renv.lock` file also changed some of the repository values, but both `CRAN` and `RSPM` are equivalent, so while I am not sure why that happened, it should have no effect.
> Add markdown to renv.lock

- scRNA-seq/07-gene_set_enrichment_analysis.Rmd
`the the` --> `the`, even though there is some play-on-words benefit to retaining both `the`s.
> Remove duplicated word

- .github/workflows/build-and-push-docker.yml
- .github/workflows/build-docker.yml
- .github/workflows/make-live.yml
- .github/workflows/render-rmds.yml
- .github/workflows/spell-check.yml
This PR adds git config instructions to allow commits and pushes in the `make-live` action. 
Closes #541
I also took the opportunity to update versions for a number of other actions, including docker build, which now natively uses the GHA cache for some simplification. Technically, this is experimental, but it seems to work well.
> Add Git configurations in GHA & update docker actions

- intro-to-R-tidyverse/02-intro_to_ggplot2.Rmd
Closes #549
Closes #556
This PR addresses two small aspects of the intro ggplot notebook, namely - 
- explain a bit more that we use `aes()` to map columns
- add in width and height to `ggsave()`
> Updated intro ggplot lesson

- intro-to-R-tidyverse/01-intro_to_base_R.Rmd
Should be lowercase! This is probably from when the notebook used `iris` instead of `penguins`.
> Species --> species

- .github/workflows/make-live.yml
- .github/workflows/render-rmds.yml
This is a small update to the rendering actions. There are two changes: 
1. prevent running for setup notebook changes. These are not actually test rendered, as they are not named in the `render-live.sh` script, so triggering the action for them seems redundant.
2. update the aws configuration action version to quiet a warning
> Update rendering actions

- scRNA-seq-advanced/setup/rms/integrate_rms.R
- scRNA-seq-advanced/setup/rms/prepare_rms_library.R
A very small PR to compress the SCE object files during the setup scripts. Using gzip compression because it is the fastest to decompress.
> Compress rds files in rms setup

- scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd
A really small PR as part of #598: 
Here I am replacing `%>%` with `|>` in the advanced/01 notebook. Apparently only used it a couple of times in that notebook, and just in one chunk!
> Use new pipe in advanced 01 notebook

- scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd
In working on the cell type exercise and using the output from the read and filter notebook, I noticed a typo in defining the output file. There was an `l` missing in `glioblastoma`. I fixed that here.
> Fix typo in output file name in 01 read and filter notebook

- components/dictionary.txt
- scRNA-seq-advanced/02-celltype_assignment.Rmd
This PR hopefully completes the Cell Typing instruction notebook, closing #567.
I added a fair amount of text, but also made a few other modifications, like switching the reference data set to the one that celldex specifically recommends for PBMCs. This meant a few changes to the ways I used `forcats`... Nothing too major, but that chunk got a lot longer. 
Other than that, a few smaller changes, but nothing too major. I briefly contemplating using `scater::ggcells()` to allow for easier customization of the plots (in particular color schemes), but decided to leave it as is for now. That didn't seem worth getting too hung up about. If somebody asks, we might want to have that in our back pockets though!
I do update to using `|>` throughout as well, and tried a brief explanation of `\(x) …
> Finish cell typing text

- components/dictionary.txt
- scRNA-seq-advanced/03-dataset_integration.Rmd
Related to #570 
This PR aims to mostly wrap up the integration instruction notebook, including...
- making chunks live (feedback welcome!)
- One thing I'm still on the fence for here is UMAP plotting. For now the first one is not live but the rest are (or at least this was my idea!). 
- removing spaces from chunk names (possibly overkill but doesn't _hurt_)
- switching over to base pipe
- spacing around code chunks
- printing objects separately from the chunks where they are made (did I go too far here?)
- other miscellaneous cleanups and text changes along the way!
Here's the rendered version: [03-dataset_integration.nb.html.zip](https://github.com/AlexsLemonade/training-modules/files/10346368/03-dataset_integration.nb.html.zip)
> Integration notebook: live chunks, pipe, and cleanups

- Dockerfile
- components/dictionary.txt
- renv.lock
- scRNA-seq-advanced/setup/README.md
- scRNA-seq-advanced/setup/pancreas/Snakefile
- scRNA-seq-advanced/setup/pancreas/config.yaml
- scRNA-seq-advanced/setup/pancreas/muraro_setup.R
- scripts/link-data.sh
- scripts/syncup-s3.sh
Related to https://github.com/AlexsLemonade/exercise-notebook-answers/issues/126, this PR adds a setup script for the Muraro pancreas data that splits and processes that data so it can be used in a merging & integration exercise.
I updated the renv.lock as well, as well as the link and sync scripts. 
Finally I updated the setup README file, and in the process noticed that the RMS data isn't described there, so I added a little stub for that, but I am probably not the best person to fill it out!
> Integration exercise setup

- components/dictionary.txt
- scRNA-seq-advanced/04-differential_expression.Rmd
- scRNA-seq-advanced/setup/README.md
- scRNA-seq-advanced/setup/rms/integrate_rms.R
Closes #573 and #610
This PR adds live chunks to the DE notebook. I also did a little bit of cleaning up on my read through with the occasional breaking up of chunks or moving text, but not too much. 
When I was doing this I also noticed that in the setup script we are using 11 libraries because we added that 1 library for integration after we did setup. However we only talk about 10 libraries in the DE notebook and it's easy to pick out the 6 libraries that we use because they share the same cell type annotations. If we included the 11th library then we would have 7 that share the same annotations. It seemed like a lot of effort to either explain why we were only using 6 of the 7 libraries that looked good or re-do the analysis with all 7 so I added a line into the integration setup …
> Enliven and clean up DE notebook with added RMS readme

- scripts/syncup-s3.sh
From this comment: https://github.com/AlexsLemonade/exercise-notebook-answers/pull/134#issuecomment-1380572498
This PR includes the myoblast DE results file in S3, since it is read in by the DE exercise so it's needed for rendering.
I did not link the data though, so participants will need to generate it on their ends.
> Sync myoblast DE tsv to s3

- scRNA-seq-advanced/setup/magic-files.md
This little PR is to add a file that will help us track any magic files that we need to create/track for the scRNA-seq-advanced module. 
At some point, this should probably be automated into a script (or rmd file with a runnable chunk) that copies the files to the correct location, but I wanted to get something started for initial tracking for now. Then we can add an issue to be sure that this is done before training.
If there are files that I missed, please let me know!
> Add a file describing magic files

- scRNA-seq-advanced/04-differential_expression.Rmd
Related to #601 
I went through the notebooks for DE instruction (both the rendered and the live version) found in #614 and found a few places that needed some shorter lines. I also noticed we had a few places where we were printing out the head of the `colData` and it was pretty ugly in the rendered version, so I just added a pipe to `as.data.frame()` to make it look better. Those are all live chunks so we don't need to print it like that when teaching unless we want to, but it definitely cleans up the output which makes for nicer rendered notebooks.
> Line length and output clean up for DE instruction

- scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd
- scRNA-seq-advanced/02-celltype_assignment.Rmd
Here I am adding a few small edits to the first two teaching notebooks for narrower rendering. 
Unlike @allyhawkins, I didn't elect to reformat `DataFrames` as `data.frames`, but I think it is fine to not be perfectly consistent here.
> Reformatting scAdvanced notebooks 1 & 2 

- scRNA-seq-advanced/03-dataset_integration.Rmd
This PR fixes small items I found in the integration notebook as described in this comment: https://github.com/AlexsLemonade/training-modules/pull/614#issuecomment-1398749573
This includes copying in the `case_when()` text we added into the exercises, but I think we should also keep that text in exercises as well since it is helpful! So, this is a copy/paste, _not_ a cut/paste.
I ended up not removing any vector printing because all of them seemed important to print!
> Small integration notebook fixes

- README.md
This PR adds a link to the DE slides in the main readme. To do this I added a new bullet for the advanced module and then a nested bullet for DE slides. I thought we could each add the links for the remaining slides in the nested bullet points. I wasn't quite sure how to organize this so am open to other thoughts.
> Add link to DE slides to main README

- scRNA-seq-advanced/03-dataset_integration.Rmd
One more round of cleanups for the integration notebook!
- I realized I still needed to clean up some live comments which looked weird without the actual code by themselves! And one live chunk at the end needed an export comment
- I unlivened a tricky `purrr` chunk that isn't critical to be live
- I removed another instance of the mediocre phrasing "in the wild"
> A couple more integration notebook fixes

- scRNA-seq-advanced/04-differential_expression.Rmd
Closes #638 
Closes #643 
Here I made some minor edits to the differential expression notebook based on some things we learned at the first training. I removed the `fitType=local` from setting up and running `DESeq` and tested that things still ran successfully. I also changed the few comments/ labels that were mentioned in #643 while I was making edits.
> Remove specifying local fit type

- module-cheatsheets/scRNA-seq-advanced-cheatsheet.md
Closes #670
Here I added a table for the SingleR functions. I did not yet rebuild the PDF, as that requires either reverting to MacDown or getting instructions from @sjspielman. Also, we might as well get the content done first.
> Add SingleR to the cheatsheet

- Dockerfile
- renv.lock
I kept playing around trying to find a way to revert #687, but I failed in that. 
However, I did discover that my change to unify on `CRAN` as the repo made things much slower than if I had unified of `RSPM`, so here I am switching over to that repo as the primary source, which should allow binary installs in the docker image, for much faster rebuilds. At least, that is how it works locally.
> Switch to RSPM in lockfile 

- scRNA-seq/05-clustering_markers_scRNA.Rmd
Closes #675
This PR updates the notebook `scRNA-seq/05-clustering_markers_scRNA.Rmd` to use `\(x)` and remove `~x`. 
At this point, `grep "~" *Rmd` in this training returns only this notebook's `-live.Rmd` and some path definitions, so we should be good after this change. 
Most of review here should just be phrasing suggestions.
> Update to 4.1 anonymous function syntax

- .github/workflows/build-and-push-docker.yml
- .github/workflows/make-live.yml
- .github/workflows/render-rmds.yml
Should do what it says, using the service account to get all of the secrets using "op://" links that are also stored as github secrets. Includes docs bot, docker, and AWS access.
> Use 1password secrets management for GHA

- renv.lock
- renv/activate.R
- renv/settings.json
This PR updates the renv version used by this repository to v1.0, and updates other installed packages to the latest versions to keep everything current.
Closes #747
I will admit this was not necessarily the smoothest update from the previous version, though it did seem to mostly work itself out by restarting the R session after pulling this branch, then running `renv::restore()` and then again restarting the R session. 
I expect running this in a fresh pull of the repository should be cleaner.
For some reason, I also had some trouble with this version not respecting the `.gitignore` files when running on the server, which means that `status` is a bit slow and throws up some warnings about the size of data directories, but I think these can be safely ignored for now if they come up. I …
> Update to renv version 1.0

- README.md
Found an old link in the README and updated it to point to https://www.ccdatalab.org/data-science-workshops. Also changed two `CCDL`s to `Data Lab`.
> Updating on old link in training-modules readme

- intro-to-R-tidyverse/00a-rstudio_guide.Rmd
Closes #752 
I updated links in the rstudio guide, and removed links whose content seems to be gone now from what I could find. I did not update screenshots though - let me know during review if you think I should! The IDE is a little different now, but we can't be updating these every time ~RStudio~ Posit changes UI styling. Plus, the panes are the same, so eh?
> Update RStudio guide

- components/dictionary.txt
This PR adds the terms `deidentified`, `onboarding`, and `PII` to the dictionary to resolve spell check errors.
> Adding terms to training-modules dictionary

- intro-to-R-tidyverse/03-intro_to_tidyverse.Rmd
- scRNA-seq/03-normalizing_scRNA.Rmd
Part of #743 
Here, I've made two changes to scIntro notebooks as noted in #743:
- https://github.com/AlexsLemonade/training-modules/issues/743#issuecomment-1589823389
- https://github.com/AlexsLemonade/training-modules/issues/743#issuecomment-1593047189 
Let me know what you think of the plot addition for the second fix!
> Fixes to tidyverse and scIntro notebooks

- .github/workflows/build-and-push-docker.yml
- .github/workflows/build-docker.yml
- .github/workflows/make-live.yml
- .github/workflows/render-rmds.yml
- Dockerfile
- renv.lock
- renv/settings.json
This PR updates all packages in `renv.lock` with the most notable overall change being the upgrade to R 4.4 and Bioconductor 3.19.
These changes have not been tested across all notebooks, so we still need #759 
closes #761
> Update to R 4.4 & Bioconductor 3.19

- scRNA-seq/04-dimension_reduction_scRNA.Rmd
Closes #768 
To avoid the negative size factors after filtering (which it turns out had been there for a while), I added a step where we recalculate the per-cell stats and re-filter. It turns out that removing some of the lowly expressed genes created cells with very low total UMI counts remaining, which affected the results. The total number of cells affected was only about 5, but I think it is a nice illustration of some of the unexpected effects of filtering!
> recalculate stats and another filtering step

- .github/workflows/build-docker.yml
- Dockerfile
- components/dependencies.R
- renv.lock
While I was wrong about https://github.com/AlexsLemonade/scpcaTools/issues/277, I had originally noticed the change when remaking output files for this repo, so here I am swapping out `fishpond` for `eds` in the `renv` for this repository. This is because the function that `tximport` uses to speed up reading alevin files has moved to `eds`. By installing `eds` we can quiet the new warning, and get faster imports.
For June 2024, I have already installed `eds` on the server, but that is not reflected here or in the docker image. I don't necessarily think we need to update the docker image, but we could if we wanted to by retagging the release (or adding a point update release).
> Swap out fishpond for eds

- gitignore.user
Closes #775
Here I am adding a user-facing gitignore file with a bit of extra security added to the one that is currently part of this repository. Most of this will probably be irrelevant in practice (ssh files should not end up in this directory unless somebody does something very odd), but part of the goal here is to show some of the scope of files you never want to include. 
I decided to name this file `gitignore.user` because that sounded better to me than `gitignore.skel`, but tell me if I am wrong!
> 775 Add user-facing gitignore.user

- intro-to-R-tidyverse/00b-debugging_resources.Rmd
- intro-to-R-tidyverse/00c-good_scientific_coding_practices.Rmd
- intro-to-R-tidyverse/01-intro_to_base_R.Rmd
- intro-to-R-tidyverse/02-intro_to_ggplot2.Rmd
- intro-to-R-tidyverse/03-intro_to_tidyverse.Rmd
- scRNA-seq-advanced/02-dataset_integration.Rmd
- scRNA-seq/05-clustering_markers_scRNA.Rmd
Closes #783 
This PR makes some small updates to intro R materials. Most changes are bumping r4ds links or fixing other broken links I found along the way. All the lesson content seemed fine, so no further changes there!
> Intro R updates

- RNA-seq/setup/magic-files.md
Since we probably want to have the full notebook for NB tximeta activity easily available just in case, let's copy it to the same magic files location.
Note that I have have also done this, moving the file that @sjspielman had initially placed in a subdirectory.
> Add instructions for copying notebook file to magic file location

- scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd
- scRNA-seq-advanced/02-dataset_integration.Rmd
- scRNA-seq-advanced/03-differential_expression.Rmd
- scRNA-seq-advanced/05-gene_set_enrichment_analysis.Rmd
Closes #692
Closes #734 
This PR updates scAdvanced notebooks by:
- using `fs::dir_create` instead of `dir.create`
- all `colour` -> `color`, and use brewer dark2 where we can
- I used the rendered notebooks as they appeared in march 2023 to determine which plots to use dark2 with:
- [refresher notebook](http://htmlpreview.github.io/?https://github.com/AlexsLemonade/training-modules/blob/2023-march/scRNA-seq-advanced/01-read_filter_normalize_scRNA.nb.html)
- [integration](http://htmlpreview.github.io/?https://github.com/AlexsLemonade/training-modules/blob/2023-march/scRNA-seq-advanced/03-dataset_integration.nb.html)
- [differential expression](http://htmlpreview.github.io/?https://github.com/AlexsLemonade/training-modules/blob/2023-march/scRNA-seq-advanced/04-differential_expression.nb.htm …
> scAdvanced updates: dir_create and plotting

- scRNA-seq-advanced/02-dataset_integration.Rmd
This PR fixes a woopsie introduced in #800, which I caught when reviewing scAdvanced materials.
I had known this at one point but forgotten - when overriding the color scale for `plotReducedDim` and friends, you need to also specify the legend title or it will default back to `colour_by`. 
This PR adds the `name` to all such spots! I also missed a few `na.value` arguments, so I added those in too. Only the integration notebook needed these changes, since we don't override the color scale itself elsewhere.
> Restore legend titles in scAdvanced integration notebook

- scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd
- scRNA-seq/04-dimension_reduction_scRNA.Rmd
Closes #804 
This PR adds the argument `col.names=TRUE` when calling `DropletUtils::read10xCounts()` so that we get nice things, like barcode column names. Let me know if we'd also like to see some text about this argument in addition to its usage.
> Keep column names when reading in 10x data

- components/dictionary.txt
- scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd
- scRNA-seq-advanced/02-dataset_integration.Rmd
- scRNA-seq-advanced/05-aucell.Rmd
- scRNA-seq/04-dimension_reduction_scRNA.Rmd
This PR moves a few comments in `live = TRUE` chunks to the end of their lines, and adds a space into a `live = TRUE`, as seen in https://github.com/AlexsLemonade/training-modules/pull/821/files
> notebook rendering fixes

- scRNA-seq-advanced/01-read_filter_normalize_scRNA.Rmd
- scRNA-seq-advanced/02-dataset_integration.Rmd
- scRNA-seq-advanced/03-differential_expression.Rmd
- scRNA-seq/01-scRNA_quant_qc.Rmd
- scRNA-seq/02-filtering_scRNA.Rmd
- scRNA-seq/03-normalizing_scRNA.Rmd
- scRNA-seq/05-clustering_markers_scRNA.Rmd
- scRNA-seq/06-celltype_annotation.Rmd
Closes #773 
This PR does some miscellaneous training material updates. Some of the items noted in #773 apparently have been fixed in the meantime, so we get those for free - I edited those comments directly to reflect that they have been done already.
Changes I made include:
- Load `alevinQC` directly (https://github.com/AlexsLemonade/training-modules/issues/773#issuecomment-2161234296)
- Use `theme_set(theme_bw())` in `scRNA-seq/03-normalizing_scRNA.Rmd`, whose plots only ever uses this theme
- Update OSCA links
- I updated other bioconductor links while doing this too, as discussed: https://github.com/AlexsLemonade/training-modules/issues/773#issuecomment-2686003590
- (edit) I did this for the scRNA-seq-advanced module too, because might as well
PSA: turn off whitespace for review, …
> Notebook fixes from June 2024

- scRNA-seq-advanced/05-aucell.Rmd
Missed this in https://github.com/AlexsLemonade/training-modules/pull/849 - I had added a seed to this notebook in #846, but turns out it already had a seed!
https://github.com/AlexsLemonade/training-modules/blob/44b975629e2274109133e8ccbd32a64593346f14/scRNA-seq-advanced/05-aucell.Rmd#L185-L192
I removed the new and unneeded seed.
After this I will re-run the GHA to render notebooks.
> Remove the extra seed
